name: html Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: html -V

  test-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: html projeto-xyz.html
        
  deploy-joy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizando!"
